### ISSUE TITLE
Song: Count spaces in .txt files

### ISSUE THREAD

**Issue by elainewlin** [elainewlin/MusicParsed#73]
* Currently, we store exact number of spaces for each chord line
* Problem: bad wrapping for smaller screens, chords disappear altogether
* Change parser.py to count number of spaces on lines
  * This way, we can use non-monospaced fonts. It preserves spacing when you transpose.
  * Link each chord to specific part of lyric line

**Comment by andersk** [comment]
[Possibly useful CSS](http://jsfiddle.net/8ytzh5Lr/).

**Comment by elainewlin** [comment]
I played around with the CSS and put up [a branch](https://github.com/elainewlin/MusicParsed/tree/align-chords-with-lyrics_%2373), but most things just look worse.

**Comment by andersk** [comment]
Yeah there are some issues with the spacing between chorded lines and non-chorded lines. This should replicate the existing spacing (modulo your change of labels from `<h4>` to `<h5>`), and we can make further tweaks from here:

```css
.line {
  font-family: "DejaVu Sans Mono", monospace;
  font-size: 16px;
  line-height: 1.5em;
  white-space: pre-wrap;
}

.chordLyricLine {
  font-family: "DejaVu Sans Mono", monospace;
  font-size: 16px;
  line-height: 3em;
  white-space: pre-wrap;
  margin: 0.75em 0 -0.75em;
}

.chords {
  color: var(--main-blue);
}

.chordLyricLine .chords {
  position: absolute;
  line-height: 0;
}
```
